::: {.callout-tip appearance="simple"}
Find this page at [bit.ly/birn-data](https://bit.ly/birn-data)
:::

# BIRN Summer School 2024

Hi, I'm [Soma](https://twitter.com/dangerscarf)! This is everything I presented at the BIRN Summer School in 2024. So far you can see:

- [Intro AI session slides](slides-intro.qmd)
- [Data analysis with Python and pandas](pandas.qmd)
- [Scraping with Python and Playwright](scraping.qmd) - [slides](slides-scraping.qmd)
- [AI for Reporting](ai-reporting.qmd) - [slides](slides-practical-ai.qmd)

### Slides

- [Data analysis with Python and pandas](pandas.qmd)
- [Scraping with Python and Playwright](scraping.qmd)
- [AI for Reporting](ai-reporting.qmd)

## Links

You can find other resources of mine at:

- [jonathansoma.com](https://jonathansoma.com/)
- [Everything I Know](https://jonathansoma.com/everything/)
- [Practical AI for Investigative Journalism](https://www.youtube.com/playlist?list=PLewNEVDy7gq1_GPUaL0OQ31QsiHP5ncAQ)
- [investigate.ai](https://investigate.ai/)
- [YouTube](https://youtube.com/@jsoma)
- [Lede Program](https://ledeprogram.com/), my 10-week summer program
- [MS in Data Journalism](https://journalism.columbia.edu/ms-data-journalism), my 12-month program

## Contact me!!!!

I love questions!! I love solving problems!!! Feel free to reach out!

- [js4571@columbia.edu](mailto:js4571@columbia.edu)
- [@dangerscarf](https://twitter.com/dangerscarf)